---
#
# Install server
#
- name: install openvpn server
  package:
    name: openvpn
    state: present

- name: install security updates
  shell: yum update-minimal --security -y

#
# iptable configuration
#
- name: add iptable_nat
  modprobe:
    name: iptable_nat
    state: present

- name: set ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: update iptables
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    source: 10.4.0.1/2
    jump: MASQUERADE

- name: update iptables
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    source: 10.8.0.0/24
    jump: MASQUERADE

#
# Key configuration
#
- name: ensure /etc/openvpn/keys
  file:
    dest: /etc/openvpn/keys
    state: directory
    mode: 0644

- name: copy cert and key files to target
  copy:
    src: "{{ item }}"
    dest: /etc/openvpn/keys/{{ item|basename }}
    mode: 0600
  with_items:
    - lib/EasyRSA-2.2.2/keys/server.crt
    - lib/EasyRSA-2.2.2/keys/server.key
    - lib/EasyRSA-2.2.2/keys/dh2048.pem
    - lib/EasyRSA-2.2.2/keys/pfs.key
    - lib/EasyRSA-2.2.2/keys/ca.crt

#
# Server config, service start
#
- name: copy server.conf to target
  copy:
    src: files/server.conf
    dest: /etc/openvpn/server.conf

- name: ensure openvpn is started
  service:
    name: openvpn
    state: restarted
